// === Turk Tili Akademiyasi - Keng Lug'at Ma'lumotlar Bazasi ===
// A1: 15 dars × 30 so'z = 450 so'z

window.vocabLessonNames = {
    'A1': {
        1:"Salomlashuv (Greetings)",
        2:"Olmoshlar (Pronouns)",
        3:"Maktab Buyumlari (School Items)",
        4:"Mevalar va Sabzavotlar (Fruits & Vegetables)",
        5:"Oila (Family)",
        6:"Sonlar (Numbers)",
        7:"Ranglar (Colors)",
        8:"Hayvonlar (Animals)",
        9:"Hafta Kunlari va Vaqt (Days & Time)",
        10:"Kiyimlar (Clothes)",
        11:"Taomlar va Ichimliklar (Food & Drinks)",
        12:"Tana A'zolari (Body Parts)",
        13:"Shahar va Joylar (City & Places)",
        14:"Ob-havo (Weather)",
        15:"Xobbi va Sport (Hobbies & Sports)"
    },
    'A2': {
        1:"Fe'llar (Verbs)", 2:"O'tgan Zamon (Past Tense)", 3:"Kelajak Zamon (Future Tense)",
        4:"Zaruriyat (Necessity)", 5:"Qiyoslash (Comparison)", 6:"Ko'makchilar (Postpositions)",
        7:"Tana va Sog'liq (Body & Health)", 8:"Kiyimlar II", 9:"Shahar II",
        10:"Sayohat (Travel)", 11:"Buyruq Mayli (Imperatives)", 12:"Murakkab O'tgan Zamon",
        13:"Umumiy Zamon (General Tense)", 14:"Kasblar (Professions)", 15:"Xobbi Iboralari"
    }
};

window.vocabularyByLesson = {
    'A1': {
        1: [
            {tr:"Merhaba", uz:"Salom"},
            {tr:"Selam", uz:"Salom (do'stona)"},
            {tr:"Günaydın", uz:"Xayrli tong"},
            {tr:"İyi günler", uz:"Xayrli kun"},
            {tr:"İyi akşamlar", uz:"Xayrli kech"},
            {tr:"İyi geceler", uz:"Xayrli tun"},
            {tr:"Hoş geldiniz", uz:"Xush kelibsiz"},
            {tr:"Hoş bulduk", uz:"Xush ko'rdik (javob)"},
            {tr:"Görüşürüz", uz:"Ko'rishguncha"},
            {tr:"Güle güle", uz:"Xayrli yo'l"},
            {tr:"Nasılsın?", uz:"Yaxshimisan?"},
            {tr:"Nasılsınız?", uz:"Yaxshimisiz?"},
            {tr:"İyiyim", uz:"Yaxshiman"},
            {tr:"Çok iyiyim", uz:"Juda yaxshiman"},
            {tr:"Fena değil", uz:"Yomon emas"},
            {tr:"Teşekkür ederim", uz:"Rahmat"},
            {tr:"Teşekkürler", uz:"Rahmat (qisqa)"},
            {tr:"Rica ederim", uz:"Arzimaydi"},
            {tr:"Özür dilerim", uz:"Kechirasiz"},
            {tr:"Pardon", uz:"Uzr so'raman"},
            {tr:"Lütfen", uz:"Iltimos"},
            {tr:"Evet", uz:"Ha"},
            {tr:"Hayır", uz:"Yo'q"},
            {tr:"Belki", uz:"Balki"},
            {tr:"Memnun oldum", uz:"Tanishganimdan xursandman"},
            {tr:"Benim adım...", uz:"Mening ismim..."},
            {tr:"Adın ne?", uz:"Isming nima?"},
            {tr:"Anlamıyorum", uz:"Tushunmayapman"},
            {tr:"Tekrar söyler misiniz?", uz:"Qayta aytasizmi?"},
            {tr:"Yavaş konuşun lütfen", uz:"Sekin gapiring iltimos"}
        ],
        2: [
            {tr:"Ben", uz:"Men"},
            {tr:"Sen", uz:"Sen"},
            {tr:"O", uz:"U"},
            {tr:"Biz", uz:"Biz"},
            {tr:"Siz", uz:"Siz"},
            {tr:"Onlar", uz:"Ular"},
            {tr:"Bu", uz:"Bu"},
            {tr:"Şu", uz:"Shu"},
            {tr:"Bunlar", uz:"Bular"},
            {tr:"Şunlar", uz:"Shular"},
            {tr:"Kim", uz:"Kim"},
            {tr:"Ne", uz:"Nima"},
            {tr:"Hangi", uz:"Qaysi"},
            {tr:"Nerede", uz:"Qayerda"},
            {tr:"Benim", uz:"Mening"},
            {tr:"Senin", uz:"Sening"},
            {tr:"Onun", uz:"Uning"},
            {tr:"Bizim", uz:"Bizning"},
            {tr:"Sizin", uz:"Sizning"},
            {tr:"Onların", uz:"Ularning"},
            {tr:"Ben kimim?", uz:"Men kimman?"},
            {tr:"Sen kimsin?", uz:"Sen kimssan?"},
            {tr:"O kimdir?", uz:"U kimdir?"},
            {tr:"Ben öğrenciyim", uz:"Men o'quvchiman"},
            {tr:"Sen öğretmensin", uz:"Sen o'qituvchisan"},
            {tr:"O doktordur", uz:"U doktor"},
            {tr:"Biz arkadaşız", uz:"Biz do'stmiz"},
            {tr:"Siz Türk müsünüz?", uz:"Siz turkmisiz?"},
            {tr:"Onlar öğrenci", uz:"Ular o'quvchi"},
            {tr:"Bu kim?", uz:"Bu kim?"}
        ],
        3: [
            {tr:"Kitap", uz:"Kitob"},
            {tr:"Defter", uz:"Daftar"},
            {tr:"Kalem", uz:"Qalam / Ruchka"},
            {tr:"Silgi", uz:"O'chirg'ich"},
            {tr:"Cetvel", uz:"Chizg'ich"},
            {tr:"Sözlük", uz:"Lug'at"},
            {tr:"Çanta", uz:"Sumka"},
            {tr:"Masa", uz:"Stol"},
            {tr:"Sandalye", uz:"Stul"},
            {tr:"Tahta", uz:"Doska"},
            {tr:"Okul", uz:"Maktab"},
            {tr:"Sınıf", uz:"Sinf"},
            {tr:"Kapı", uz:"Eshik"},
            {tr:"Pencere", uz:"Deraza"},
            {tr:"Ders", uz:"Dars"},
            {tr:"Öğretmen", uz:"O'qituvchi"},
            {tr:"Öğrenci", uz:"O'quvchi"},
            {tr:"Kağıt", uz:"Qog'oz"},
            {tr:"Kalemlik", uz:"Qalamdon"},
            {tr:"Boyalar", uz:"Bo'yoqlar"},
            {tr:"Makas", uz:"Qaychi"},
            {tr:"Yapıştırıcı", uz:"Yelim"},
            {tr:"Kitaplık", uz:"Kitob javoni"},
            {tr:"Bilgisayar", uz:"Kompyuter"},
            {tr:"Tebeşir", uz:"Bo'r"},
            {tr:"Harita", uz:"Xarita"},
            {tr:"Küre", uz:"Globus"},
            {tr:"Sınav", uz:"Imtihon"},
            {tr:"Not", uz:"Baho"},
            {tr:"Ödev", uz:"Uy vazifasi"}
        ],
        4: [
            {tr:"Elma", uz:"Olma"},
            {tr:"Armut", uz:"Nok"},
            {tr:"Muz", uz:"Banan"},
            {tr:"Portakal", uz:"Apelsin"},
            {tr:"Üzüm", uz:"Uzum"},
            {tr:"Çilek", uz:"Qulupnay"},
            {tr:"Karpuz", uz:"Tarvuz"},
            {tr:"Kavun", uz:"Qovun"},
            {tr:"Şeftali", uz:"Shaftoli"},
            {tr:"Kiraz", uz:"Gilos"},
            {tr:"Vişne", uz:"Olcha"},
            {tr:"İncir", uz:"Anjir"},
            {tr:"Erik", uz:"O'rik"},
            {tr:"Nar", uz:"Anor"},
            {tr:"Limon", uz:"Limon"},
            {tr:"Mandalina", uz:"Mandarin"},
            {tr:"Ananas", uz:"Ananas"},
            {tr:"Mango", uz:"Mango"},
            {tr:"Kivi", uz:"Kivi"},
            {tr:"Ceviz", uz:"Yong'oq"},
            {tr:"Badem", uz:"Bodom"},
            {tr:"Fıstık", uz:"Yeryong'oq"},
            {tr:"Kestane", uz:"Kashtan"},
            {tr:"Meyve suyu", uz:"Meva sharbati"},
            {tr:"Sebze", uz:"Sabzavot"},
            {tr:"Domates", uz:"Pomidor"},
            {tr:"Salatalık", uz:"Bodring"},
            {tr:"Havuç", uz:"Sabzi"},
            {tr:"Patlıcan", uz:"Baqlajon"},
            {tr:"Biber", uz:"Qalampir"}
        ],
        5: [
            {tr:"Anne", uz:"Ona"},
            {tr:"Baba", uz:"Dada"},
            {tr:"Kardeş", uz:"Aka / uka / opa / singil"},
            {tr:"Abla", uz:"Opa"},
            {tr:"Abi", uz:"Aka"},
            {tr:"Kız kardeş", uz:"Singil"},
            {tr:"Erkek kardeş", uz:"Uka"},
            {tr:"Dede", uz:"Bobo"},
            {tr:"Büyükanne", uz:"Buvijon"},
            {tr:"Nene", uz:"Buvi"},
            {tr:"Amca", uz:"Amaki (dada tomoni)"},
            {tr:"Dayı", uz:"Tog'a (ona tomoni)"},
            {tr:"Hala", uz:"Amma (dada tomoni)"},
            {tr:"Teyze", uz:"Xola (ona tomoni)"},
            {tr:"Kuzen", uz:"Amakivachcha / xolavacha"},
            {tr:"Gelin", uz:"Kelin"},
            {tr:"Damat", uz:"Kuyov"},
            {tr:"Torun", uz:"Nevara"},
            {tr:"Bebek", uz:"Chaqaloq"},
            {tr:"Çocuk", uz:"Bola"},
            {tr:"Genç", uz:"Yosh"},
            {tr:"Yaşlı", uz:"Keksa"},
            {tr:"Aile", uz:"Oila"},
            {tr:"Ev", uz:"Uy"},
            {tr:"Evcil hayvan", uz:"Uy hayvoni"},
            {tr:"Sevgili", uz:"Sevgilim"},
            {tr:"Eş", uz:"Turmush o'rtoq"},
            {tr:"Koca", uz:"Er"},
            {tr:"Karı", uz:"Xotin"},
            {tr:"Akraba", uz:"Qarindosh"}
        ],
        6: [
            {tr:"Sıfır", uz:"Nol (0)"},
            {tr:"Bir", uz:"Bir (1)"},
            {tr:"İki", uz:"Ikki (2)"},
            {tr:"Üç", uz:"Uch (3)"},
            {tr:"Dört", uz:"To'rt (4)"},
            {tr:"Beş", uz:"Besh (5)"},
            {tr:"Altı", uz:"Olti (6)"},
            {tr:"Yedi", uz:"Yetti (7)"},
            {tr:"Sekiz", uz:"Sakkiz (8)"},
            {tr:"Dokuz", uz:"To'qqiz (9)"},
            {tr:"On", uz:"O'n (10)"},
            {tr:"On bir", uz:"O'n bir (11)"},
            {tr:"On iki", uz:"O'n ikki (12)"},
            {tr:"Yirmi", uz:"Yigirma (20)"},
            {tr:"Otuz", uz:"O'ttiz (30)"},
            {tr:"Kırk", uz:"Qirq (40)"},
            {tr:"Elli", uz:"Ellik (50)"},
            {tr:"Altmış", uz:"Oltmish (60)"},
            {tr:"Yetmiş", uz:"Yetmish (70)"},
            {tr:"Seksen", uz:"Sakson (80)"},
            {tr:"Doksan", uz:"To'qson (90)"},
            {tr:"Yüz", uz:"Yuz (100)"},
            {tr:"Bin", uz:"Ming (1000)"},
            {tr:"Milyon", uz:"Million"},
            {tr:"Kaç tane?", uz:"Nechta?"},
            {tr:"Kaç yaşındasın?", uz:"Yoshing nechada?"},
            {tr:"Birinci", uz:"Birinchi"},
            {tr:"İkinci", uz:"Ikkinchi"},
            {tr:"Üçüncü", uz:"Uchinchi"},
            {tr:"Sonuncu", uz:"Oxirgi"}
        ],
        7: [
            {tr:"Kırmızı", uz:"Qizil"},
            {tr:"Mavi", uz:"Ko'k"},
            {tr:"Yeşil", uz:"Yashil"},
            {tr:"Sarı", uz:"Sariq"},
            {tr:"Beyaz", uz:"Oq"},
            {tr:"Siyah", uz:"Qora"},
            {tr:"Turuncu", uz:"To'q sariq / Apelsin rangi"},
            {tr:"Mor", uz:"Binafsha"},
            {tr:"Pembe", uz:"Pushti"},
            {tr:"Kahverengi", uz:"Jigarrang"},
            {tr:"Gri", uz:"Kulrang"},
            {tr:"Gümüş rengi", uz:"Kumush rangi"},
            {tr:"Altın rengi", uz:"Oltin rangi"},
            {tr:"Lacivert", uz:"To'q ko'k"},
            {tr:"Açık mavi", uz:"Och ko'k"},
            {tr:"Koyu yeşil", uz:"To'q yashil"},
            {tr:"Bordo", uz:"To'q qizil"},
            {tr:"Bej", uz:"Bej rang"},
            {tr:"Krem rengi", uz:"Krem rang"},
            {tr:"Renkli", uz:"Rangli"},
            {tr:"Renksiz", uz:"Rangsiz"},
            {tr:"Hangi renk?", uz:"Qaysi rang?"},
            {tr:"Favori rengim", uz:"Sevimli rangim"},
            {tr:"Kırmızı araba", uz:"Qizil mashina"},
            {tr:"Mavi gökyüzü", uz:"Ko'k osmon"},
            {tr:"Yeşil yaprak", uz:"Yashil barg"},
            {tr:"Sarı güneş", uz:"Sariq quyosh"},
            {tr:"Beyaz kar", uz:"Oq qor"},
            {tr:"Siyah gece", uz:"Qora tun"},
            {tr:"Pembe çiçek", uz:"Pushti gul"}
        ],
        8: [
            {tr:"Kedi", uz:"Mushuk"},
            {tr:"Köpek", uz:"Kuchuk / It"},
            {tr:"Kuş", uz:"Qush"},
            {tr:"Balık", uz:"Baliq"},
            {tr:"At", uz:"Ot"},
            {tr:"İnek", uz:"Sigir"},
            {tr:"Koyun", uz:"Qo'y"},
            {tr:"Keçi", uz:"Echki"},
            {tr:"Tavuk", uz:"Tovuq"},
            {tr:"Horoz", uz:"Xo'roz"},
            {tr:"Ördek", uz:"O'rdak"},
            {tr:"Kaz", uz:"G'oz"},
            {tr:"Aslan", uz:"Sher"},
            {tr:"Kaplan", uz:"Yo'lbars"},
            {tr:"Fil", uz:"Fil"},
            {tr:"Zürafa", uz:"Jirafa"},
            {tr:"Maymun", uz:"Maymun"},
            {tr:"Ayı", uz:"Ayiq"},
            {tr:"Kurt", uz:"Bo'ri"},
            {tr:"Tilki", uz:"Tulki"},
            {tr:"Tavşan", uz:"Quyon"},
            {tr:"Fare", uz:"Sichqon"},
            {tr:"Yılan", uz:"Ilon"},
            {tr:"Kaplumbağa", uz:"Toshbaqa"},
            {tr:"Kurbağa", uz:"Qurbaqa"},
            {tr:"Arı", uz:"Ari"},
            {tr:"Kelebek", uz:"Kapalak"},
            {tr:"Karınca", uz:"Chumoli"},
            {tr:"Örümcek", uz:"O'rgimchak"},
            {tr:"Yunus balığı", uz:"Delfin"}
        ],
        9: [
            {tr:"Pazartesi", uz:"Dushanba"},
            {tr:"Salı", uz:"Seshanba"},
            {tr:"Çarşamba", uz:"Chorshanba"},
            {tr:"Perşembe", uz:"Payshanba"},
            {tr:"Cuma", uz:"Juma"},
            {tr:"Cumartesi", uz:"Shanba"},
            {tr:"Pazar", uz:"Yakshanba"},
            {tr:"Bugün", uz:"Bugun"},
            {tr:"Yarın", uz:"Ertaga"},
            {tr:"Dün", uz:"Kecha"},
            {tr:"Hafta", uz:"Hafta"},
            {tr:"Hafta sonu", uz:"Ish kuni boshligi"},
            {tr:"Ay", uz:"Oy"},
            {tr:"Yıl", uz:"Yil"},
            {tr:"Sabah", uz:"Ertalab"},
            {tr:"Öğle", uz:"Peshin"},
            {tr:"Akşam", uz:"Kechqurun"},
            {tr:"Gece", uz:"Tun"},
            {tr:"Şimdi", uz:"Hozir"},
            {tr:"Sonra", uz:"Keyin"},
            {tr:"Önce", uz:"Oldin"},
            {tr:"Saat kaç?", uz:"Soat necha?"},
            {tr:"Sabah erken", uz:"Erta tongda"},
            {tr:"Geç kalmak", uz:"Kech qolmoq"},
            {tr:"Zaman", uz:"Vaqt"},
            {tr:"Dakika", uz:"Daqiqa"},
            {tr:"Saniye", uz:"Soniya"},
            {tr:"Takvim", uz:"Taqvim"},
            {tr:"Tatil", uz:"Dam olish"},
            {tr:"Bugün ne günü?", uz:"Bugun qaysi kun?"}
        ],
        10: [
            {tr:"Gömlek", uz:"Ko'ylak (erkaklar)"},
            {tr:"Bluz", uz:"Bluzka (ayollar)"},
            {tr:"Pantolon", uz:"Shim"},
            {tr:"Etek", uz:"Yubka"},
            {tr:"Elbise", uz:"Ko'ylak (ayollar)"},
            {tr:"Ceket", uz:"Pidjak"},
            {tr:"Mont", uz:"Palto"},
            {tr:"Kazak", uz:"Sviter"},
            {tr:"Hırka", uz:"Kardigan"},
            {tr:"Tişört", uz:"Futbolka"},
            {tr:"Ayakkabı", uz:"Oyoq kiyim"},
            {tr:"Bot", uz:"Etik"},
            {tr:"Terlik", uz:"Shippak"},
            {tr:"Spor ayakkabı", uz:"Krossovka"},
            {tr:"Çorap", uz:"Paypoq"},
            {tr:"Şapka", uz:"Shlyapa"},
            {tr:"Bere", uz:"Qalpoq"},
            {tr:"Atkı", uz:"Sharflash"},
            {tr:"Eldiven", uz:"Qo'lqop"},
            {tr:"Çanta", uz:"Sumka"},
            {tr:"Kemer", uz:"Kamar"},
            {tr:"Güneş gözlüğü", uz:"Quyosh ko'zoynagi"},
            {tr:"Kravat", uz:"Galstuk"},
            {tr:"İç çamaşırı", uz:"Ichki kiyim"},
            {tr:"Pijama", uz:"Pijama"},
            {tr:"Yağmurluk", uz:"Yomg'irpush"},
            {tr:"Jean pantolon", uz:"Jinsi shim"},
            {tr:"Kolye", uz:"Marjonlar"},
            {tr:"Küpe", uz:"Sirg'a"},
            {tr:"Yüzük", uz:"Uzuk"}
        ],
        11: [
            {tr:"Ekmek", uz:"Non"},
            {tr:"Süt", uz:"Sut"},
            {tr:"Su", uz:"Suv"},
            {tr:"Çay", uz:"Choy"},
            {tr:"Kahve", uz:"Qahva"},
            {tr:"Şeker", uz:"Shakar"},
            {tr:"Tuz", uz:"Tuz"},
            {tr:"Yağ", uz:"Yog'"},
            {tr:"Peynir", uz:"Pishloq"},
            {tr:"Yumurta", uz:"Tuxum"},
            {tr:"Tavuk eti", uz:"Tovuq go'shti"},
            {tr:"Et", uz:"Go'sht"},
            {tr:"Pilav", uz:"Palov / Guruch"},
            {tr:"Çorba", uz:"Sho'rva"},
            {tr:"Salata", uz:"Salat"},
            {tr:"Makarna", uz:"Makaron"},
            {tr:"Pizza", uz:"Pitsa"},
            {tr:"Hamburger", uz:"Gamburger"},
            {tr:"Meyve suyu", uz:"Meva sharbati"},
            {tr:"Ayran", uz:"Qatiq (ichimlik)"},
            {tr:"Elma çayı", uz:"Olma choyi"},
            {tr:"Bitki çayı", uz:"O'simliklar choyi"},
            {tr:"Kahvaltı", uz:"Nonushta"},
            {tr:"Öğle yemeği", uz:"Tushlik"},
            {tr:"Akşam yemeği", uz:"Kechki ovqat"},
            {tr:"Tatlı", uz:"Shirinlik / Desert"},
            {tr:"Acı", uz:"Achchiq"},
            {tr:"Tuz", uz:"Sho'r"},
            {tr:"Ekşi", uz:"Nordon"},
            {tr:"Lezzetli", uz:"Mazali"}
        ],
        12: [
            {tr:"Baş", uz:"Bosh"},
            {tr:"Yüz", uz:"Yuz"},
            {tr:"Göz", uz:"Ko'z"},
            {tr:"Kulak", uz:"Quloq"},
            {tr:"Burun", uz:"Burun"},
            {tr:"Ağız", uz:"Og'iz"},
            {tr:"Diş", uz:"Tish"},
            {tr:"Dil", uz:"Til"},
            {tr:"Boyun", uz:"Bo'yin"},
            {tr:"Omuz", uz:"Yelka"},
            {tr:"Kol", uz:"Qo'l (yuqori qism)"},
            {tr:"Dirsek", uz:"Tirsak"},
            {tr:"El", uz:"Kaft"},
            {tr:"Parmak", uz:"Barmoq"},
            {tr:"Tırnak", uz:"Tirnoq"},
            {tr:"Göğüs", uz:"Ko'krak"},
            {tr:"Karın", uz:"Qorin"},
            {tr:"Bel", uz:"Bel"},
            {tr:"Sırt", uz:"Orqa"},
            {tr:"Bacak", uz:"Oyoq (yuqori qism)"},
            {tr:"Diz", uz:"Tizza"},
            {tr:"Ayak", uz:"Oyoq panjasi"},
            {tr:"Topuk", uz:"Tovon"},
            {tr:"Saç", uz:"Soch"},
            {tr:"Kaş", uz:"Qosh"},
            {tr:"Kirpik", uz:"Kiprik"},
            {tr:"Çene", uz:"Jag'"},
            {tr:"Yanak", uz:"Yonoq"},
            {tr:"Alın", uz:"Peshona"},
            {tr:"Kalp", uz:"Yurak"}
        ],
        13: [
            {tr:"Şehir", uz:"Shahar"},
            {tr:"Köy", uz:"Qishloq"},
            {tr:"Mahalle", uz:"Mahalla"},
            {tr:"Sokak", uz:"Ko'cha"},
            {tr:"Cadde", uz:"Katta ko'cha / Prospekt"},
            {tr:"Park", uz:"Park"},
            {tr:"Okul", uz:"Maktab"},
            {tr:"Hastane", uz:"Kasalxona"},
            {tr:"Eczane", uz:"Dorixona"},
            {tr:"Market", uz:"Do'kon"},
            {tr:"Banka", uz:"Bank"},
            {tr:"Postane", uz:"Pochta"},
            {tr:"Kütüphane", uz:"Kutubxona"},
            {tr:"Müze", uz:"Muzey"},
            {tr:"Cami", uz:"Masjid"},
            {tr:"Restoran", uz:"Restoran"},
            {tr:"Kafe", uz:"Kafe"},
            {tr:"Otel", uz:"Mehmonxona"},
            {tr:"Havalimanı", uz:"Aeroport"},
            {tr:"Tren istasyonu", uz:"Poyezd bekat"},
            {tr:"Otogar", uz:"Avtobus bekati"},
            {tr:"Meydan", uz:"Maydon"},
            {tr:"Köprü", uz:"Ko'prik"},
            {tr:"Deniz", uz:"Dengiz"},
            {tr:"Nehir", uz:"Daryo"},
            {tr:"Dağ", uz:"Tog'"},
            {tr:"Orman", uz:"O'rmon"},
            {tr:"Sağda", uz:"O'ngda"},
            {tr:"Solda", uz:"Chapda"},
            {tr:"Düz gidin", uz:"To'g'ri boring"}
        ],
        14: [
            {tr:"Hava", uz:"Ob-havo / Havo"},
            {tr:"Güneş", uz:"Quyosh"},
            {tr:"Güneşli", uz:"Quyoshli"},
            {tr:"Bulut", uz:"Bulut"},
            {tr:"Bulutlu", uz:"Bulutli"},
            {tr:"Yağmur", uz:"Yomg'ir"},
            {tr:"Yağmurlu", uz:"Yomg'irli"},
            {tr:"Kar", uz:"Qor"},
            {tr:"Karlı", uz:"Qorli"},
            {tr:"Rüzgar", uz:"Shamol"},
            {tr:"Rüzgarlı", uz:"Shamolli"},
            {tr:"Sis", uz:"Tuman"},
            {tr:"Sisli", uz:"Tumanli"},
            {tr:"Fırtına", uz:"Bo'ron"},
            {tr:"Şimşek", uz:"Chaqmoq"},
            {tr:"Gök gürültüsü", uz:"Momaqaldiroq"},
            {tr:"Don", uz:"Ayoz"},
            {tr:"Sıcak", uz:"Issiq"},
            {tr:"Soğuk", uz:"Sovuq"},
            {tr:"Ilık", uz:"Iliq"},
            {tr:"Sıcaklık", uz:"Harorat"},
            {tr:"Derece", uz:"Gradus / Daraja"},
            {tr:"Mevsim", uz:"Fasl"},
            {tr:"İlkbahar", uz:"Bahor"},
            {tr:"Yaz", uz:"Yoz"},
            {tr:"Sonbahar", uz:"Kuz"},
            {tr:"Kış", uz:"Qish"},
            {tr:"Hava tahmini", uz:"Ob-havo ma'lumoti"},
            {tr:"Bugün hava nasıl?", uz:"Bugun havo qanday?"},
            {tr:"Sıcaklık kaç derece?", uz:"Harorat necha gradus?"}
        ],
        15: [
            {tr:"Hobi", uz:"Qiziqish / Hobby"},
            {tr:"Müzik", uz:"Musiqa"},
            {tr:"Müzik dinlemek", uz:"Musiqa tinglash"},
            {tr:"Şarkı söylemek", uz:"Qo'shiq aytish"},
            {tr:"Dans etmek", uz:"Raqs tushish"},
            {tr:"Resim yapmak", uz:"Rasm chizish"},
            {tr:"Kitap okumak", uz:"Kitob o'qish"},
            {tr:"Sinema", uz:"Kino"},
            {tr:"Film izlemek", uz:"Film ko'rish"},
            {tr:"Oyun oynamak", uz:"O'yin o'ynash"},
            {tr:"Bilgisayar oyunları", uz:"Kompyuter o'yinlari"},
            {tr:"Spor yapmak", uz:"Sport bilan shug'ullanish"},
            {tr:"Futbol", uz:"Futbol"},
            {tr:"Basketbol", uz:"Basketbol"},
            {tr:"Tenis", uz:"Tennis"},
            {tr:"Yüzmek", uz:"Suzish"},
            {tr:"Koşmak", uz:"Yugurish"},
            {tr:"Bisiklet sürmek", uz:"Velosiped minish"},
            {tr:"Yürüyüş yapmak", uz:"Sayr qilish"},
            {tr:"Fotoğraf çekmek", uz:"Rasm olish"},
            {tr:"Bahçeyle uğraşmak", uz:"Bog'da ishlash"},
            {tr:"Yemek pişirmek", uz:"Oshpazlik qilish"},
            {tr:"Seyahat etmek", uz:"Sayohat qilish"},
            {tr:"Dil öğrenmek", uz:"Til o'rganish"},
            {tr:"Yoga yapmak", uz:"Yoga qilish"},
            {tr:"Meditasyon yapmak", uz:"Meditatsiya qilish"},
            {tr:"Satranç oynamak", uz:"Shaxmat o'ynash"},
            {tr:"Müzik aleti çalmak", uz:"Musiqa asbobi chalish"},
            {tr:"Gönüllü çalışmak", uz:"Ko'ngilli ishlash"},
            {tr:"Koleksiyon yapmak", uz:"Kollektsiya to'plash"}
        ]
    },
    'A2': {
        1: [
            {tr:"Gitmek", uz:"Ketmoq"},
            {tr:"Gelmek", uz:"Kelmoq"},
            {tr:"Yapmak", uz:"Qilmoq"},
            {tr:"Okumak", uz:"O'qimoq"},
            {tr:"Yazmak", uz:"Yozmoq"},
            {tr:"Konuşmak", uz:"Gapirmoq"},
            {tr:"Dinlemek", uz:"Eshitmoq / Tinglash"},
            {tr:"Görmek", uz:"Ko'rmoq"},
            {tr:"Duymak", uz:"Eshitmoq / Sezmoq"},
            {tr:"Anlamak", uz:"Tushunmoq"},
            {tr:"Bilmek", uz:"Bilmoq"},
            {tr:"Sevmek", uz:"Sevmoq"},
            {tr:"İstemek", uz:"Xohlamoq"},
            {tr:"Söylemek", uz:"Aytmoq"},
            {tr:"Düşünmek", uz:"O'ylamoq"},
            {tr:"Bakmak", uz:"Qaramoq"},
            {tr:"Yemek", uz:"Yemoq"},
            {tr:"İçmek", uz:"Ichmoq"},
            {tr:"Uyumak", uz:"Uxlamoq"},
            {tr:"Çalışmak", uz:"Ishlash / O'qish"},
            {tr:"Oynamak", uz:"O'ynash"},
            {tr:"Koşmak", uz:"Yugurish"},
            {tr:"Yürümek", uz:"Yurish"},
            {tr:"Gülmek", uz:"Kulmoq"},
            {tr:"Ağlamak", uz:"Yig'lamoq"},
            {tr:"Söylemek", uz:"Aytmoq"},
            {tr:"Almak", uz:"Olmoq"},
            {tr:"Vermek", uz:"Bermoq"},
            {tr:"Bulmak", uz:"Topmoq"},
            {tr:"Kaybetmek", uz:"Yo'qotmoq"}
        ]
    }
};
